name: pointnet-env
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch
    - fastapi
    - uvicorn
    - pandas
    - scikit-learn
    - mlflow
    - azureml-core
    - azureml-mlflow
    - azureml-inference-server-http
    - azure-ai-ml