name: Train and Deploy PointNet

on:
  push:
    paths:
      - 'ml/train/**'
      - 'ml/models/**'
      - 'data/preprocessed/**'
      - '.github/workflows/train_and_deploy.yml'

permissions:
  id-token: write
  contents: read

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch pandas scikit-learn azureml-core mlflow

      - name: Train model and log with MLflow
        run: python ml/train/train_pointnet.py

      - name: Deploy to ACI
        run: python deployment/deploy_aci.py